# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 1 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: canftin
          template: classic
          base: header
          base_indepth: yes
          config_order: base.header
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: user
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
         
      - name: 🦑 Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: canftin
          organization: MatrixWood, modern-lambda, Eros-Engine, SummerDB, pud-lang, HybridQuanta
          base: ""
          config_order: base.header, isocalendar, languages
          #plugin_achievements: yes
          #plugin_achievements_display: compact
          plugin_fortune: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: commit, pull_request, issue
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, javascript, java
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 3
          plugin_languages_indepth: yes
          commits_authoring: CanftIn, canftin, canftin@users.noreply.github.com
